name: luddang
version: '${version}'
main: org.luddang.Luddang
api-version: '1.20'
libraries:
  - "net.kyori:adventure-api:4.17.0"
  - "net.kyori:adventure-platform-bukkit:4.3.2"
  - "net.kyori:adventure-text-minimessage:4.17.0"
commands:
  ld:
